### ISSUE TITLE
Aptitude Tests section design suggestion

### ISSUE THREAD

**Issue by Mayur-Nandu** [yashtibrewal/portfolio-website#10]
![image](https://user-images.githubusercontent.com/40487787/162559321-62379835-2ae4-4a96-9ac7-66419b7e4018.png)
 
 1. make sure the logos are of same size and center aligned.
 2. when writing the score also add the maximum score achievable. eg 310/350 or covert each score to percentage and display it for better consistency.

**Comment by yashtibrewal** [comment]
Feel free to use labels for the issues

**Comment by yashtibrewal** [comment]
2. N/A
