### ISSUE TITLE
Add SSL certificate

### ISSUE THREAD

**Issue by Mayur-Nandu** [yashtibrewal/portfolio-website#13]
![image](https://user-images.githubusercontent.com/40487787/162559492-c0a97467-f846-4610-9709-662a658c9402.png)

**Comment by yashtibrewal** [comment]
I do not see the need for a SSL certificate yet.

**Comment by yashtibrewal** [comment]
Mayur I am not able to add a SSL certificate, could you please guide me. I want to do it, but its difficult. I am stuck up with it. Just a link to a good blog to add SSL on localhost will do. PLEASE.
