### ISSUE TITLE
design suggeestion 

### ISSUE THREAD

**Issue by Mayur-Nandu** [yashtibrewal/portfolio-website#14]
![image](https://user-images.githubusercontent.com/40487787/162559670-e4548a90-2bfc-4052-a701-667d884e9cf7.png)
![image](https://user-images.githubusercontent.com/40487787/162559692-edca84a0-23be-4235-a574-e01f27c8a351.png)

Too many colors used try to keep the website color pallet limited to few colors preferably 2  or 3.

**Comment by yashtibrewal** [comment]
done.
