### ISSUE TITLE
Footer Suggestions

### ISSUE THREAD

**Issue by Mayur-Nandu** [yashtibrewal/portfolio-website#17]
![image](https://user-images.githubusercontent.com/40487787/162559904-51762563-59ce-4844-ae65-b4c91f738cdc.png)

1. Make sure the footer text is aligned properly (the text and icons should be in one line)
2. Make the icons clickable as well.
3. For Email use "mailto" attribute with appropriate subject and body so that when some one clicks on the email hyperlink their mailbox is opened.
4. Use "tel" attribute for phone number so the user can directly call you if user is browsing your website on mobile.

**Comment by yashtibrewal** [comment]
1. Not interested to try.
2. Done
3. N/A
4. N/A
