### ISSUE TITLE
use proper sementics

### ISSUE THREAD

**Issue by Mayur-Nandu** [yashtibrewal/portfolio-website#19]
![image](https://user-images.githubusercontent.com/40487787/162560278-78060a11-db5e-410c-81a6-77cae141bb65.png)
![image](https://user-images.githubusercontent.com/40487787/162560405-c247994f-3470-450e-912c-5b98899c4af7.png)

1. Quick Learner is a text it should be inside a Paragraph tag or Heading tag or span tag.
2. Preferably Quick Learner should be in a h2/h3 tag so that your hierarchy of the website is maintained.
3. use <footer> tag for footer

**Comment by yashtibrewal** [comment]
how to use tag for footer? @Mayur-Nandu
